single-cell-data/SOMA

README.md

Q1 Roadmap

---

specification.md

Relevant bullets from *Notes:* have been folded into the appropriate data model description. One exception: the note about implementation-specific details is now a footnote (but we can do something different if there's opposition to the use of footnotes). 
This moves the `sc_group` diagram closer to its description and closes #19.

Consolidate data model description and notes

---

python-spec/README.md
python-spec/pyproject.toml
python-spec/setup.py
python-spec/src/somabase/__init__.py

- Adds more information to the `pyproject.toml`.
- Adds a README.
- formats everything with `black` and `isort`.
---
Just a little more uncontroversial stuff before I get to the meat of things.

Finalize some infrastructure stuff for the specification.

---

abstract_specification.md

As we discussed. See also https://github.com/single-cell-data/TileDB-SOMA/pull/537 and https://github.com/single-cell-data/TileDB-SOMA/pull/538.

Remove SOMADataFrame; rename SOMAIndexedDataFrame to SOMADataframe

---

abstract_specification.md

Initial draft of the section describing the various lifecycle labels used to annotate SOMA classes and methods. Feedback and suggestions are welcome.
Related to https://github.com/single-cell-data/TileDB-SOMA/issues/487 and [sc-23225].

Add lifecycle stages section

---

abstract_specification.md

Here’s the first part of the results of our discussion about platform configuration and a “context” type. This defines the structure of the config itself and then after this we can start working more on the structure and semantics of Context. Feedback very welcome!

Add basic description of `platform_config`.

---

abstract_specification.md

Incorporates feedback from the initial PR (#47) and includes example lifecycle annotations for a class, method, and parameter.
Let me know if there are alternative suggestions for the proposed annotation convention.

Refine lifecycle labels

---

abstract_specification.md

As on https://github.com/single-cell-data/TileDB-SOMA/issues/484

Specify semantics of index-by-empty-list

---

abstract_specification.md

Specify double inclusivity for slices

---

abstract_specification.md

For consistency where we use all caps for initialisms, replace NdArray with NDArray (cf. SomaWhatever vs. SOMAWhatever).
---
Courting controversy with this one.

NdArray → NDArray

---

python-spec/src/somabase/data.py
python-spec/src/somabase/options.py

This adds metadata to the base SOMA objects and specifies the major read/write operations of the data storage classes: the NDArrays and DataFrame.
Lifecycle management (opening, closing, etc.) will be coming in future changes.

python: Build out base data storage ABCs.

---

python-spec/src/somacore/__init__.py

In support of draft PR https://github.com/single-cell-data/TileDB-SOMA/issues/669

Export ReadIter and SparseRead

---

python-spec/src/somacore/__init__.py
python-spec/src/somacore/ephemeral.py
python-spec/testing/test_ephemeral.py
python-spec/testing/test_wrap.py

This implements a Collection that just stores its contents in memory. Suitable for ad-hoc work and combining data from different sources short-term.

Add a basic "ephemeral" SOMA collection.

---

.github/workflows/python-somacore.yaml
python-spec/.gitignore
python-spec/requirements-py3.10.txt
python-spec/requirements-py3.7.txt
python-spec/requirements-py3.8.txt
python-spec/requirements-py3.9.txt
python-spec/update-requirements-txt

These enable dependency caching in Python setup steps.

Create requirements.txt files for each version of Python.

---

abstract_specification.md
python-spec/src/somacore/data.py

Change NDArray ndims to ndim

---

python-spec/src/somacore/experiment.py
python-spec/src/somacore/query/axis.py

Allow passing `None` to `Experiment.axis_query`.

---

python-spec/src/somacore/data.py

[python] Fix `soma_type` on `SparseNDArray`.

---

abstract_specification.md
python-spec/src/somacore/data.py

Described fully at https://github.com/single-cell-data/SOMA/issues/121

Clarify non-negative `soma_joinid` in docstring and spec

---

python-spec/src/somacore/options.py
python-spec/src/somacore/query/axis.py
python-spec/testing/test_query_axis.py

This PR is to #138 as impl-repo https://github.com/single-cell-data/TileDB-SOMA/pull/968 is to https://github.com/single-cell-data/TileDB-SOMA/pull/985

[python] Add support for timestamp types in axis query

---

python-spec/src/somacore/experiment.py
python-spec/src/somacore/query/query.py

Related to single-cell-data/TileDB-SOMA#976 - add missing lifecycle maturity tags
Also, fixed a minor TODO related to typing.

add lifecycle maturity tags

---

python-spec/src/somacore/query/axis.py
python-spec/src/somacore/query/query.py

Context: https://github.com/single-cell-data/TileDB-SOMA/issues/1041

[python] Trivial doc-neatens in prep for web publishing

---

python-spec/README.md
python-spec/src/somacore/query/_fast_csr.py
python-spec/src/somacore/query/axis.py
python-spec/src/somacore/query/query.py

a fun thing to do is to forget that some of your code lives in subdirectories

[python] Also convert query docstrings to Google format

---

python-spec/src/somacore/data.py
python-spec/src/somacore/options.py
python-spec/src/somacore/query/axis.py
python-spec/src/somacore/query/query.py

https://github.com/single-cell-data/TileDB-SOMA/issues/1089

[python] More lifecycle-experimental and doc-link updates

---

python-spec/src/somacore/options.py
python-spec/src/somacore/query/query.py

Iterative work on https://github.com/single-cell-data/TileDB-SOMA/issues/1089

[docs] More doc-styling

---

python-spec/src/somacore/ephemeral/collections.py
python-spec/src/somacore/experiment.py
python-spec/src/somacore/measurement.py
python-spec/src/somacore/scene.py

This PR provides a proposed restructuring to the spatial components.

Proposed update to the spatial additions

---

python-spec/src/somacore/experiment.py
python-spec/src/somacore/measurement.py
python-spec/src/somacore/scene.py

* Make `obsl` and `varl` collections
* Remove `obssm` and `varsm` collections (duplicates `obsl` and `varl`)
* Rename `obs_spatial` -> `obs_scene` and `var_spatial` to `var_scene`

Small modifications to the spatial layout

---

python-spec/src/somacore/__init__.py
python-spec/src/somacore/coordinates.py
python-spec/src/somacore/ephemeral/__init__.py
python-spec/src/somacore/ephemeral/collections.py
python-spec/src/somacore/images.py
python-spec/src/somacore/query/query.py
python-spec/src/somacore/scene.py
python-spec/testing/test_collection.py

This PR adds a prototype image collection. The following decisions should be reviewed:
* Proposed API
* Naming choices

Prototype image collection

---

python-spec/src/somacore/coordinates.py
python-spec/src/somacore/ephemeral/collections.py
python-spec/src/somacore/options.py
python-spec/src/somacore/scene.py
python-spec/testing/test_coordinates.py

* Add methods to Scene for registering assets and getting the transforms to assets
* In CoordinateTransform change  `__mul__`, `__rmul__` to `__matmul__`, `__rmatmul__`
* Clean-up some docstrings/formatting

Small clean-up of spatial API

---

.github/workflows/python-somacore.yaml

This broke just today:
https://github.com/single-cell-data/SOMA/actions/runs/13678559750
Moving forward with advice from @teo-tsirpanis .
https://github.com/single-cell-data/TileDB-SOMA/issues/3720
[[sc-63626]](https://app.shortcut.com/tiledb-inc/story/63626/tiledb-soma-1-16-0)

New PyPI uploader workflow required
