specification.md
Extending discussion here: https://github.com/single-cell-data/matrix-api/issues/11
* This would change the sequence and first introduce `sc_group` & `sc_dataset` and then talk about the specification within `sc_group`.
* It would make identifications with existing formats on the level of `sc_group` and not on the level of the fields within `sc_group`.
There is also a question here regarding "allowing arbitrary collections of dataframes" vs. aligned multi-dimensional annotations (https://github.com/single-cell-data/matrix-api/issues/3).
=> Suggestion re introducing sc_group vs sc_dataset

abstract_specification.md
SOMASparseNdArray did not clearly indicate the semantics of the `get nnz` operation.  This specifies that it returns the number of stored values, _including_ any explicitly stored zeros.  It also clarifies that implicitly stored values are zero.
Also fixed a small typo in a parameter value (s/col-major/column-major/)
=> clarify get nnz behavior for SOMASparseNdArray

abstract_specification.md
Adding simplicity to SOMADenseNdArray `read` and `write`:
* values specified as an Arrow Tensor
* coordinates specified as a per-dimension list of scalar or range/slice
* specify dense subarray read/write (not sparse or scatter)
=> simplification of SOMADenseNdArray read and write interface

python-spec/.gitignore, python-spec/pyproject.toml, python-spec/setup.py, python-spec/src/somabase/__init__.py
This sets up the infrastructure for where we can put the base classes and whatever other Python stuff we need as we develop the SOMA spec. It's about the simplest possible Python project with the minimal amount of needed stuff.
---
I’m not too attached to the name, just that `somabase` was my best idea since `soma` and `singlecell` are both already taken.
=> Add the very basic skeleton where the Python spec will go.

python-spec/src/somabase/base.py
These are the most core types in the spec, what we need to build everything else.
---
Figure I’ve got to start somewhere so it might as well be here. This is deceptively simple but there are a few decisions we’ll be making here that set some directions.
My biggest question here is about naming:
My default strategy is to name most things without the `SOMA` prefix on front, because they can be accessed by users as `somabase.Whatever`, and otherwise we have a bunch of `somabase.SOMAThingOne` and `somabase.SOMAThingTwo` running around, where we already know things belong to SOMA. This preference is influenced by my past use of the [Google Python style guide](https://google.github.io/styleguide/pyguide.html#22-imports), which mandates importing only modules, not things within modules, so names …
=> Add the basic SOMA Object and Collection types.

python-spec/pyproject.toml, python-spec/src/somabase/__init__.py, python-spec/src/somabase/options.py
Adds the "common interfaces" `IOfN`, `BatchSize`, and `BatchFormat`. These classes are the exact values that implementations will use, i.e. an implementation of the SOMA API will not implement its own `IOfN` or any of these other “option” types.
These types are implemented using the `attrs` package, essentially an enhanced version of the built-in `dataclasses` package. It is very lightweight and already extensively used within the Python ecosystem so it will not add much (if anything) to the size of a typical installed environment.
---
I started on the API structure for the various NDArray types and found that we needed some options before then.
The major decision here was the way I chose to implement `BatchSize`. Instead of e.g. two different types (like maybe `CountBatch(n)` and …
=> Add concrete classes and enums for options.

abstract_specification.md
Changes:
* All offset types (`soma_rowid`, `soma_joinid`) changed from uint64 to positive int64.
* Remove `reshape` operation from the NdArray types.
* Clarify schema type conformance and promotion behavior, particularly with regard to Arrow's `string` and `large_string`
* NdArray COO column names - add `soma` prefix to move all names into the reserved namespace.
* Clarify explicit nature of `soma_rowid` / `soma_joinid` handling throughout.
Optional review:  @ambrosejcarr
=> incorporate discussion from 20221007 design review meeting

abstract_specification.md
`type` as a name is easy to confuse for (and imo would better fit as) the data type that is stored in an array/dataframe/whatever, rather than just the name of the thing itself. Renaming it `soma_type` will make it clearer that it refers to the SOMA object type, and also allow us to use `type` for a more user-relevant name in the future.
=> Rename `type` getter to `soma_type`.

python-spec/pyproject.toml, python-spec/src/somabase/__init__.py, python-spec/src/somabase/base.py, python-spec/src/somabase/data.py, python-spec/src/somabase/options.py
Split off from #56. This adds the data storage types (DataFrame, the NDArrays), but does not include the more complex read/write parts of the API. This will allow us to build things that refer to these types without waiting for the exact details of how reading and writing are implemented.
=> python: Add basis of data storage types

python-spec/src/somabase/__init__.py, python-spec/src/somabase/base.py, python-spec/src/somabase/data.py
Abstract properties can be fulfilled by setting an attribute on the class itself, and using `Final` makes the type checker yell if you try to change it.
---
This used to be a much fancier idea that used descriptors to do more or less the same thing, but it would also ensure that nobody would change it at runtime. (That would have looked like this: https://github.com/single-cell-data/SOMA/commit/967ff84cdf30bb82b8caec84ad46097270e6dd13.) I don’t think the additional code there is worth it, though, since Final gives us (and users) static analysis security (and if users *do* start monkeying around with SOMA internals, if they break it they get to keep both pieces).
=> Shorten up constant declarations with `Final`.

python-spec/src/somabase/_wrap.py, python-spec/src/somabase/base.py, python-spec/src/somabase/composed.py, python-spec/testing/test_wrap.py
This change implements the Measurement "behavior class" in two steps:
1. Creates a collection proxy that can be used as a base class to decorate Collections with additional behaviors.
- Also a descriptor object that makes writing attribute-to-indexing bridges trivial.
2. Implements Measurement using the proxy and the descriptors.
From here, implementing the other composed classes is quite straightforward. Once all are complete, TileDB-SOMA will no longer need to use its own custom implementation of Experiment and Measurement and can instead use the common wrapper classes around its own Collection objects.
---
This is the first part of the Grand Plan to separate behavior from storage. I’m sure there are parts of it that I have not explained quite as well as I had hoped so I am happy for …
=> Add tools to create simple composed types and implement Measurement

abstract_specification.md
One of the first questions users ask about a single-cell dataset is "how many cells and how many genes are in here?"
We need to let people answer this question.
This is essential for uptake UX.
=> Add SOMADataFrame count accessor

python-spec/.gitignore, python-spec/pyproject.toml, python-spec/setuptools-scm.toml, python-spec/src/somacore/__init__.py, python-spec/src/somacore/_version.py, python-spec/write-version-file
Because our project is not at the root of our Git repository, we can't use straight `setuptools_scm`, so we do a little extra work.
- When building a package for release, run `write-version-file` before running `build`/`twine`.
- After that, everything works like normal.
---
A slightly different solution than we use in `TileDB-SOMA` but lets us have a purely declarative `pyproject.toml`, with just a bit of extra work in the build process.
=> Set up project versioning for PyPI upload.

python-spec/pyproject.toml, python-spec/src/somacore/py.typed
In order for mypy to use the types in an installed package's code for type-checking purposes, it needs this marker file.  See, for example, https://github.com/python/mypy/blob/master/mypy/py.typed
=> Add `py.typed` marker file for downstream type checking.

python-spec/pyproject.toml, python-spec/src/somacore/__init__.py, python-spec/src/somacore/composed.py, python-spec/src/somacore/query/axis.py, python-spec/src/somacore/query/query.py, python-spec/testing/test_query_axis.py
First adds the very basics of the `Experiment` wrapper type, then adds the interface for `AxisExperimentQuery`.
To elaborate on this from the commit message:
> Because there is no TileDB-specific behavior in `ExperimentAxisQuery`, I believe we can actually pull the entire implementation here (it only uses the properties of Experiment itself) but that is for a later date.
I think this may actually be *necessary*—because of the “wrap, don’t extend” design of the `Measurement` and `Experiment` types (where they are implemented to be a proxy around any existing `Collection` rather than to be subclassed as a separate parent of a concrete `Collection` implementation), we want to provide the implementation so that in the SOMA library, it looks like:
```python
exp_collection = load_collection() …
```
=> Add `Experiment` base type and `AxisExperimentQuery`.

LICENSE, python-spec/pyproject.toml
Adds TileDB to the copyright file and sets MIT license metadata.
=> Update licensing information for PyPI publishing.

python-spec/src/somacore/data.py, python-spec/src/somacore/query/query.py
- Changes `ids`, `slices`, and `coords` to all be just `coords`
- Adds appropriate annotations for each type.
---
To see what this will look like when it propagates to `tiledbsoma`: https://github.com/single-cell-data/TileDB-SOMA/commit/ad1cbaeab348ba53e8b10df41098ade574e719ef
=> Make all coordinates `coords` and add type annotations.

.pre-commit-config.yaml, python-spec/src/somacore/__init__.py, setup.py
- In the process of moving python installation config to the root on #80, I missed the `setup.py` file. This re-adds it to make ediable installs work again.
- Adds a mypy pre-commit step.
=> Re-enable `pip install --editable`; add mypy pre-commit step.

.gitignore, pyproject.toml, python-spec/requirements-py3.10.txt, python-spec/requirements-py3.7-lint.txt, python-spec/requirements-py3.7.txt, python-spec/requirements-py3.8.txt, python-spec/requirements-py3.9.txt, python-spec/src/somacore/data.py, python-spec/src/somacore/query/eager_iter.py, python-spec/src/somacore/query/fast_csr.py, python-spec/src/somacore/query/query.py
This PR addresses the peformance issues noted in single-cell-data/TileDB-SOMA#719.  In particular, loading large AnnData requires CSR sparse matrices, which are very slow to convert from COO to CSR.  This PR adds a fast-path converter for Python, implementing two changes:
* parallelized COO to CSR conversion
* eager reading of the COO data from SOMA, allowing some concurrent COO-to-CSR work to overlap with the data reading.
In addition, this change uses substantially less memory for the conversion, allowing larger datasets to be loaded into CSR, and therefore into AnnData.
Before/after benchmarks show 1.5-4X speed-ups when the work fits in RAM (tested on r6i instance types with data on S3).  In cases where paging occured, speed-ups were dramatically larger (e.g., 20X).
See also, related …
=> [python] Fast CSR loading for to_anndata

python-spec/src/somacore/query/query.py
Fixes single-cell-data/TileDB-SOMA#768
The access to the query indexer public API was accidentally removed during the move of code into `somacore`.  This PR adds the function back to the class as a property.
=> [python] Make ExperimentAxisQuery.indexer public

python-spec/src/somacore/_wrap.py, python-spec/src/somacore/base.py, python-spec/src/somacore/ephemeral.py
Also pulls the `set` method for Collections from TileDB-SOMA, allowing a user to decide whether a collection entry should be stored with an absolute or relative URI.
This is the first step in reworking the SOMA object creation and opening protocols with the eventual goal that (unless the user does something weird) user code should only ever have to deal with fully-set-up SOMA objects and collections.
---
My biggest question here is: Does it make sense to import the `set` method from tiledbsoma?
=> Create `add` method for base Collection type

.pre-commit-config.yaml, python-spec/src/somacore/query/eager_iter.py, python-spec/src/somacore/query/query.py
Shamelessly stolen from the TileDB SOMA repository [1], this change adds ruff to the pre-commit workflow.
Also does some minor changes to placate ruff so we start off with a completely clean slate.
[1] https://github.com/single-cell-data/TileDB-SOMA/pull/751
(cc @gsakkis)
=> Add ruff (a fast Python linter) to pre-commit.

python-spec/src/somacore/__init__.py, python-spec/src/somacore/_wrap.py, python-spec/src/somacore/composed.py, python-spec/src/somacore/data.py, python-spec/src/somacore/ephemeral.py, python-spec/src/somacore/query/__init__.py, python-spec/src/somacore/query/_eager_iter.py, python-spec/src/somacore/query/_fast_csr.py, python-spec/src/somacore/query/axis.py, python-spec/src/somacore/query/fast_csr.py, python-spec/src/somacore/query/query.py, python-spec/testing/test_query_axis.py
- Changes everything to use relative imports, since in a small package just using `from . import whatever` makes more sense than full-path imports.
- Makes "private modules whose exports can be used by other somacore code" vs. "private members within a single module" a bit clearer by making module names private.
Expanded details on both are in each commit’s message. The external API (provided users weren’t using the undocumented internal APIs) remains unchanged.
=> [python] Make imports relative and shuffle privacy underscores around.

python-spec/src/somacore/base.py, python-spec/src/somacore/collection.py, python-spec/src/somacore/data.py, python-spec/src/somacore/options.py
This is (the specification side of) the plan for reworking the way we do creating and building complex SOMA objects. Currently, the primary model in TileDB-SOMA is to create the "leaf" objects, then work your way out to creating the "root" objects. This change is intended to better support a top-down creation model, where a user can create (for example) an Experiment, then create the members inside of it:
```python
new_exp = soma_impl.Experiment.create("uri/of/new/experiment", ...)
new_exp.add_dataframe("obs", ...)
```
It also includes a changed flow for opening SOMA objects, where the SOMA object should always refer to a known object, rather than potentially being a free-floating URI:
```python
my_coll = soma_impl.Collection.open("/path/to/whatever", ...)
```
This is also intended to …
=> Rework object-creation and collection-building protocols

python-spec/src/somacore/base.py, python-spec/src/somacore/query/_eager_iter.py, python-spec/src/somacore/query/query.py
This adds a `close` method to SOMAObject, which allows implementations to specify cleanup operations, and hooks it up to the context manager protocol by default.
Also cleans up other delete callsites to do our own delete work *before* calling the superclass delete.
=> Add `close` method and context-manager operations

python-spec/src/somacore/query/_fast_csr.py, python-spec/src/somacore/query/query.py
Several small changes to ensure that empty query results have types that are compatible with AnnData, avoiding warnings/errors from AnnData.
1. The empty matrix result in the fast CSR builder was creating an empty float64 matrix.  AnnData has a strong preference for float32, and will issue a warning on anything else.  As the actual type is relatively immaterial (it is an empty matrix), this PR changes to float32 to minimize complaints from AnnData.
2. The axis dataframes need to have an index type of str.  Previous code did not work correctly when the dataframe was empty.
3. When the resulting X is empty (nnz==0), need to ensure it has the same shape as the axis.
Fixes: single-cell-data/TileDB-SOMA#805
=> Empty query results typing

python-spec/src/somacore/base.py, python-spec/src/somacore/collection.py, python-spec/src/somacore/data.py, python-spec/src/somacore/experiment.py, python-spec/src/somacore/measurement.py
When using `@property` declarations, the type system would not realize that in the implementation, `soma_type` could always be accessed as a class variable. This change just makes `soma_type` a class var and shuffles around some annotations to make that easier. The `is_sparse` field on `NDArray` is similarly updated.
---
This idea came to me in the shower.
=> Declare `soma_type` as a class var rather than a property.

pyproject.toml, python-spec/src/somacore/query/_fast_csr.py, python-spec/testing/test_collection.py
- Require setting codes on type-ignore comments.
- Warn on unnecessary typecasts.
- Check functions without type information.
=> [python] Enhance type-checking configuration

python-spec/src/somacore/__init__.py, python-spec/src/somacore/collection.py, python-spec/src/somacore/ephemeral/__init__.py, python-spec/src/somacore/ephemeral/collections.py, python-spec/src/somacore/experiment.py, python-spec/src/somacore/measurement.py, python-spec/testing/test_collection.py, python-spec/testing/test_mixin.py
The meaning and usage of the various `SimpleWhatever` collections was unclear with them colocated with the abstract implementation. Moving them to their own `ephemeral` module and not having them in the main `somacore` namespace will make them less attractive. They still have value in being the most basic possible implementation of a collection, and are useful in tests for this package.
In the process of removing the `SimpleCollection` export from the package root, also changes the `__init__.py` to just import module members rather than the module itself. Since this is at the top level and is exclusively for re-export, this does not have the same potential circular dependency problems as doing so within internal modules, while reducing repetition and the possibility of errors.
=> Pull "ephemeral" collections into their own module.

python-spec/README.md
This should fix the broken link on pypi.org project page (https://pypi.org/project/somacore/)
=> Make link to abstract spec absolute in README

python-spec/src/somacore/query/axis.py, python-spec/testing/test_query_axis.py
Because our backend now supports string and bytes queries [1], we no longer need to reject them at the input stage. Also adds more tests.
[1]: https://github.com/single-cell-data/TileDB-SOMA/pull/861
---
Related to: https://github.com/single-cell-data/TileDB-SOMA/issues/419
=> Add support for str and bytes in AxisQuery

python-spec/src/somacore/collection.py, python-spec/src/somacore/ephemeral/collections.py, python-spec/src/somacore/experiment.py, python-spec/src/somacore/measurement.py, python-spec/src/somacore/query/query.py
Context: https://github.com/single-cell-data/TileDB-SOMA/issues/638 and https://github.com/single-cell-data/TileDB-SOMA/issues/540
- Pulls basic collection impl into `BaseCollection`, allowing `Collection` to add the semantics of "no semantics". This mirrors the implementation in `tiledbsoma`.
- Makes `Measurement` and `Experiment` inherit from `BaseCollection`. Previous problems with this were due to missing `__slots__`.
- Adds generic parameters to `Measurement` and `Experiment` that allow implementations to specify the exact types they provide, saving a lot of `cast`ing down the road.
- Renames lots of TypeVars to be clearer about their purpose.
- Adds overloads to `add_new_collection` for better type inference.
- Tightens `_Experimentish` to only expect read accessors, not writers. …
=> Rework and enhance type hierarchy and generics

python-spec/src/somacore/__init__.py, python-spec/src/somacore/query/__init__.py
This is the `somacore` have of the solution for https://github.com/single-cell-data/TileDB-SOMA/issues/791.
Once this is in place and a `python-v0.0.0a11` is tagged, we can have `tiledbsoma` re-export `AxisColumnNames`.
=> Export `AxisColumnNames`

python-spec/src/somacore/base.py, python-spec/src/somacore/collection.py, python-spec/src/somacore/data.py, python-spec/src/somacore/ephemeral/collections.py
- Adds `mode`, `close`, and `closed` methods/properties.
- Fills in most of the docstrings with details about parameters and expected behavior.
---
This change depends upon the result of https://github.com/single-cell-data/TileDB-SOMA/pull/910.
Part of #107 and https://github.com/single-cell-data/TileDB-SOMA/issues/638.
=> [python] Add missing lifecycle methods and expand docstrings

python-spec/src/somacore/collection.py, python-spec/src/somacore/data.py, python-spec/src/somacore/ephemeral/collections.py
Returns `self` from a few methods to enable chaining:
- DataFrame/DenseNDArray/SparseNDArray.write
- Collection.set
This enables useful chaining:
some_coll.set('x', ...).set('y', ...)
my_df = DataFrame.create(...).write(...)
do_stuff_with(my_df)
---
I remember this being something we discussed a while back that got lost in other things, so here it is back again.
=> [python] Enable chaining on certain write methods.

python-spec/src/somacore/options.py, python-spec/src/somacore/types.py
This removes `None` from the `SparseNDCoords` type (since we now accept `()` as the "return everything" value) and separates a singular `SparseNDCoord` type out from it.
Also introduces a generic `Slice` protocol, since there is no stdlib-based type annotation for "a slice of a given type". This is, unfortunately, still not useful at runtime, since `slice` is always going to resolve to `Slice[Any]`, but the annotation is useful for specification purposes.
---
This is a roundabout part of fixing https://github.com/single-cell-data/TileDB-SOMA/issues/933.
=> Add new supported types and improve precision of coordinates

python-spec/src/somacore/query/axis.py, python-spec/src/somacore/types.py, python-spec/testing/test_types.py
Gives `is_normal_sequence` a slightly better name and makes it available to packages importing somacore.
---
Another thing for https://github.com/single-cell-data/TileDB-SOMA/issues/933. This will make sense eventually.
=> Make `is_nonstringy_sequence` available in `types`.

abstract_specification.md
This formalizes the object lifecycle and the various creation, opening, and closing methods we are already using in the tiledbsoma Python implementation.
See #107.
=> [spec] Specify object lifecycle and related operations

python-spec/src/somacore/types.py, python-spec/testing/test_types.py
Since `range` has the members `start`/`stop`/`step`, that meant that `isinstance(range(x), Slice)` would return True, when a `range` is *not* a `Slice`.  Using `abc` and manually registering `slice` fixes this.
This also unrestricts `Slice`s from being `Comparable`, since the built-in `slice` type does not have this restriction, and adds the `is_slice_of` function, taken from `tiledbsoma`.
=> [python] Make `Slice` protocol not `runtime_checkable`

python-spec/src/somacore/types.py
We don't use it anymore, and it is not useful for static analysis (you only need to implement a subset of the methods to support all comparisons) nor at runtime (every object implements all of the `__xx__` methods, but most return `NotImplemented`, meaning that `isinstance(anything, Comparable)` was always true even for things that were not comparable, like regular old `object()`.
=> Remove the `Comparable` protocol.

.github/workflows/python-somacore.yaml
Every single run of the `upload-to-pypi` task, I would see:
Post job cleanup.
Error: Unexpected end of JSON input
and I had no idea why. But looking at the `setup-python` step:
cache: pip
cache-dependency-path: python-spec/requirements-py.txt
check-latest: false
token: ***
update-environment: true
There is no `requirements-py.txt` file, because there is no `matrix` to get a `matrix.python-version` from, because it's not a matrixed step.
=> Correctly specify the pip cache in the Github workflow.

MANIFEST.in, pyproject.toml, python-spec/src/somacore/ephemeral/collections.py, python-spec/src/somacore/options.py, python-spec/src/somacore/types.py, python-spec/testing/test_types.py
In order to actually have ruff do your isorting, you have to enable the `I` error codes. This does that. Also fixes a line in the MANIFEST file.
=> [python] Re-enable isort via ruff; fix `MANIFEST.in`

abstract_specification.md, python-spec/src/somacore/data.py, python-spec/src/somacore/options.py
Implements the spec side of the plan laid out in issue https://github.com/single-cell-data/TileDB-SOMA/issues/931.
This PR addresses only explicit shaping of `SparseNDArray` -- explicit shaping of `DataFrame` will be on a separate PR.
=> Mutable-X mods, and explicit shaping of `SparseNDArray`

python-spec/src/somacore/options.py, python-spec/src/somacore/query/axis.py, python-spec/testing/test_query_axis.py
As of recently [1], TileDB-SOMA now supports floats when indexing dataframes.  We should no longer forbid them in axis queries.
[1]: https://github.com/single-cell-data/TileDB-SOMA/pull/968
Context: issue https://github.com/single-cell-data/TileDB-SOMA/issues/960
=> [python] Add support for floats in axis query

python-spec/src/somacore/options.py, python-spec/src/somacore/query/axis.py, python-spec/testing/test_query_axis.py
This adds boolean to the supported sparse coordinate types and also improves the type definition of coordinate types to ensure that the values in each type are homogeneous:
BadCoord = Union[int, str]
BadCoords = Union[BadCoord, Sequence[BadCoord]]
GoodCoord = TypeVar("GoodCoord", int, str)
GoodCoords = Union[GoodCoord, Sequence[GoodCoord]]
---
I don’t see a bug entry for this but it was something we discussed earlier today, and in the process I realized another thing we could improve.
Context: #960
=> [python] Add `bool` to supported types and improve type specification

python-spec/src/somacore/data.py
Context: https://github.com/single-cell-data/TileDB-SOMA/issues/961
This is a prerequisite for https://github.com/single-cell-data/TileDB-SOMA/pull/1027.
Note that for `SparseNDArray` it sufficed to have a slotwise int `shape`: indexing is only by `int64` and we took the min to be 0, leaving only the max to be specified. Here, for `DataFrame`, indices can be of various types so we truly must do parameterizations in terms of domains -- min-max pairs on each dim slot.
=> [python] Explicit shaping for `DataFrame`

python-spec/src/somacore/collection.py
Companion to https://github.com/single-cell-data/TileDB-SOMA/pull/1045.
=> Change collection child type to "kind" name.

python-spec/src/somacore/options.py
My previous change which used TypeVar for coordinate types [1] was actually a Bad Idea.  While it was better in that it prohibited heterogeneous collections and slices, it was worse in that made the SparseDFCoord type (and derived types) into generic types, which we do not want.
The *right* way to avoid repeating all the possible types is to make a union of the possible *containers*, and then specify *that* with all the possible contents that may go into those containers.
[1]: https://github.com/single-cell-data/SOMA/pull/141
=> Don't use `TypeVar` when defining coordinate types

python-spec/src/somacore/base.py, python-spec/src/somacore/collection.py, python-spec/src/somacore/data.py, python-spec/src/somacore/experiment.py, python-spec/src/somacore/measurement.py, python-spec/src/somacore/types.py
This also expands the docstrings for Experiment and Measurement.
---
In this change, I also changed the format of maturity levels to make them look like just another docs stanza. If we don’t like it, it can be reverted to the `[lifecycle: whatever]` style.
Part of https://github.com/single-cell-data/TileDB-SOMA/issues/974.
=> [python] Convert docstrings to Google style

abstract_specification.md, python-spec/src/somacore/query/query.py
Resolves https://github.com/single-cell-data/TileDB-SOMA/issues/834
Resolves https://github.com/single-cell-data/SOMA/issues/133
=> API spec-compliance fixes

abstract_specification.md, python-spec/src/somacore/measurement.py
As discussed in the March 31 2023 spec meeting.
See also https://github.com/single-cell-data/TileDB-SOMA/issues/1245.
=> Allow `obsm` and `varm` to be stored sparsely

rfcs/README.md
This directory can be used to capture design documents and proposals about the SOMA spec and can be used as a source of truth to revisit technical decisions in a central location.
=> Add initial directory and README for SOMA RFCs/design docs.

python-spec/src/somacore/options.py
This incorporates the specification changes from this commit: 89692959e9112d9cf1323cf0521a4cf0fa1efa49
into the Python implementation.
We restrict the multi-platform–compatible type to be specifically a ``dict`` (and not a ``Mapping``) so that if some implementation had a configuration that implemented Mapping, it would be excluded (i.e., we only look inside basic built-in types and no funny business).
=> Update `PlatformConfig` to allow impl-specific types

python-spec/src/somacore/base.py, python-spec/src/somacore/collection.py, python-spec/src/somacore/data.py, python-spec/src/somacore/experiment.py, python-spec/src/somacore/measurement.py, python-spec/src/somacore/query/axis.py, python-spec/src/somacore/query/query.py
Related to single-cell-data/TileDB-SOMA#1402
Update public API lifecycle tags from `experimental` to `maturing`
**Note to reviewers:** please consider if there are any exceptions to this update (i.e., API that should remain `experimental`).
See also:  single-cell-data/TileDB-SOMA#1405
=> [Python] update lifecycle tags

python-spec/src/somacore/query/query.py
Resolves https://github.com/single-cell-data/TileDB-SOMA/issues/1527
Testing will done on tiledbsoma (link TBD)
=> [python] Add parameters to `ExperimentAxis` query methods

python-spec/src/somacore/types.py
After talking just now I was looking at the protocol and wondered: Why do we not just say `class Slice(Protocol[_T_co]): start: Optional[_T_co]` etc.? The [`Named` example protocol](https://docs.python.org/3/library/typing.html#typing.runtime_checkable) in the Python docs uses that syntax.
Then I tried it and found out why.
=> Add a note about why the fields of Slice are `@property`s.

python-spec/src/somacore/query/query.py, python-spec/testing/test_query_axis.py
This aims to eliminate the annoyance (and potential error) of writing
thing = whatever.obs if axis is _Axis.OBS else whatever.var
by letting you say
thing = axis.getattr_from(whatever)
instead.
=> Add `_Axis.getattr_from` and `_Axis.getitem_from`.

python-spec/src/somacore/query/_fast_csr.py, python-spec/src/somacore/query/query.py, python-spec/src/somacore/query/types.py
To support a custom indexer in TileDB-SOMA, this introduces a basic abstraction that is used to build the Indexer used by the CSR Accumulator.  This can then be easily overridden by an implementation's custom subclass to swap that out without having to duplicate substantial parts of the code.
The naming is, admittedly, not ideal; this is in part due to the naming of the things we're trying to abstract over (the Pandas `Index` type which has the `get_indexer` method).
---
This is the somacore counterpart of https://github.com/single-cell-data/TileDB-SOMA/pull/1728. It *is* entirely compatible with current code, though; once we’re positive that it fufills the needs of the tiledb-soma reindexer, we can merge it and release it and tiledbsoma installations will continue to work fine.
=> Allow overriding of CSR accumulators with an `IndexLike`

python-spec/src/somacore/query/_eager_iter.py, python-spec/testing/test_eager_iter.py
Previously, if you provided a thread pool that was too small and an EagerIterator could not create a new preloading thread, the iterator would deadlock, since it would wait for the new thread to be created forever and not try to just do the work itself. This change instead uses preloading as an optional optimization, and if the preload has not yet been completed, computes the next value itself.
=> Prevent deadlocks in EagerIterators by making prefetch optional.

python-spec/src/somacore/options.py
For discussion, cf. https://github.com/single-cell-data/TileDB-SOMA/issues/1791, cc @johnkerl @bkmartinjr.
What more might we want to do here? Existing TileDB-SOMA tests pass with and without this change, see https://github.com/single-cell-data/TileDB-SOMA/pull/2234
=> Add `pa.ChunkedArray` to `SparseNDCoord` type

python-spec/src/somacore/query/types.py
We only use the `target` positional argument from the pandas `Index.get_indexer` method. Remove optional keyword arguments to allow greater flexibility when implementing a `IndexLike` class.
=> Remove optional keyword args from `IndexLike.get_indexer`

python-spec/src/somacore/query/query.py
In support of https://github.com/single-cell-data/TileDB-SOMA/issues/2473
=> Allow `obs_query`/`var_query=None` syntax

.github/workflows/python-somacore.yaml, pyproject.toml, python-spec/update-requirements-txt
Following on
* https://github.com/single-cell-data/TileDB-SOMA/pull/2181
* https://github.com/single-cell-data/TileDB-SOMA/issues/1790
We should have done the same for this repo, and did not
=> Drop Python 3.7 support

pyproject.toml, python-spec/src/somacore/query/query.py
This is a prototype implementation for getting scene IDs from the obs or var index on an experiment query axis for testing purposes.
Issue: [#2592](https://github.com/single-cell-data/TileDB-SOMA/issues/2592)
=> Add first pass at obs/var to scene implementation

python-spec/src/somacore/query/query.py
In prep for upcoming spatial-transcriptomics work, which will be tagged experimental.
See also https://github.com/single-cell-data/TileDB-SOMA/pull/2807
=> Use `Lifecycle: maturing` for query `obsm`/`varm`

python-spec/src/somacore/query/query.py
**Issue:**
https://github.com/single-cell-data/TileDB-SOMA/issues/2765
**Changes:**
`ExperimentAxisQuery.to_anndata` iterates through each column and drops unused categories.
**Notes for Reviewer:**
This change was originally proposed in https://github.com/single-cell-data/TileDB-SOMA/pull/2811 but was suggested somacore was a more appropriate location for it.
=> Drop unused categories in `ExperimentAxisQuery.to_anndata`

python-spec/src/somacore/query/query.py
I made a docstring correction to https://github.com/single-cell-data/SOMA/pull/204 and then merged immediately assuming that it would not affect CI, but it failed the formatting check.
=> Correct formatting for `to_anndata` doc string

.pre-commit-config.yaml, pyproject.toml, python-spec/src/somacore/_mixin.py, python-spec/src/somacore/collection.py, python-spec/src/somacore/query/query.py, python-spec/src/somacore/types.py
Update linter versions, set target Python version for linters to Python 3.8, and address new linter errors.
Lint fixes:
* Add pandas stub
* Remove call to deprecated `pd.api.types.is_categorical_dtype`
* Add type annotation for numpy array variable
* Update pyproject.toml ruff syntax
* Black format changes
=> Update pre-commit linters and new lint errors

python-spec/src/somacore/query/query.py
`ad.{obs,var}[name]` is always type `pd.Series`. We need to use `.dtype` to check the type of the column.
The original code used `pd.api.types.is_categorical_dtype` but that function is now deprecated.
---
```
(soma-3.11) vivian@mangonada:~/SOMA$ git log -1 --oneline
5ca6d91 (HEAD -> vn/correct-category-check, origin/vn/correct-category-check) Correct category dtype check in `ExperimentAxisQuery`
(soma-3.11) vivian@mangonada:~/TileDB-SOMA$ pip show somacore
Name: somacore
Version: 1.0.14.dev1+g402b2bc.d20240809
Summary: Python-language API specification and base utilities for implementation of the SOMA system.
Home-page:
Author:
Author-email:
License:
Location: /home/vivian/anaconda3/envs/soma-3.11/lib/python3.11/site-packages
Requires: anndata, attrs, numba, numpy, pandas, pyarrow, …
```
=> Correct category dtype check in `ExperimentAxisQuery`

pyproject.toml, python-spec/requirements-py3.10.txt, python-spec/requirements-py3.11.txt, python-spec/requirements-py3.12.txt, python-spec/requirements-py3.8-lint.txt, python-spec/requirements-py3.8.txt, python-spec/requirements-py3.9.txt, python-spec/src/somacore/__init__.py, python-spec/src/somacore/data.py, python-spec/src/somacore/ephemeral/collections.py, python-spec/src/somacore/options.py, python-spec/src/somacore/scene.py
Changes:
* Add a new GeometryDataFrame class
* Adds shapely as a somacore Python dependency.
WIP:
* How we want to handle the two-dimensional geometry index dimension for both schema specification needs further investigation.
Issues: Closes https://github.com/single-cell-data/TileDB-SOMA/issues/2677
=> Python spec for geometry dataframe

python-spec/src/somacore/__init__.py, python-spec/src/somacore/coordinates.py, python-spec/testing/test_coordinates.py
This moves the implementation of the `Axis`, `CoordinateSpace`, and `CoordinateTransform` class from TileDB-SOMA to SOMA. It also adds a `ScaleTransform` class.
=> Add full implementation of CoordinateSpace and CoordinateTransform

python-spec/src/somacore/__init__.py, python-spec/src/somacore/ephemeral/__init__.py, python-spec/src/somacore/ephemeral/collections.py, python-spec/src/somacore/images.py, python-spec/src/somacore/scene.py, python-spec/testing/test_collection.py
This PR cleans up the multiscale image pyramid class. It includes the following:
=> Replace somacore `ImageCollection` and `Image2DCollection` with `MultiscaleImage` 

python-spec/src/somacore/__init__.py, python-spec/src/somacore/coordinates.py, python-spec/src/somacore/options.py, python-spec/src/somacore/spatialdata.py, python-spec/testing/test_coordinates.py
* Update API for `MultiscaleImage.read_level` method
* Add `SpatialDataFrame.read_region` method 
* Fix composition (`__mul__`, `__rmul__`) in the coordinate transform classes
* Add methods to return inverse of the coordinate transform classes
* Remove apply methods from the coordinate transform classes
=> Update API for spatial reads and fix CoordinateTransforms

python-spec/src/somacore/query/query.py
This addresses a bug in the `ExperimentAxisQuery` anndata exporter that is specific to `obsm`/`varm` arrays.
Currently, the number of columns needed for the resulting numpy array is taken from the `SparseNDArray`'s shape property, which provides the maximum capacity of the underlying TileDB array, rather than the occupied capacity. This results in the exporter allocating a far larger numpy `ndarray` than necessary when obsm/varm layers are included in the output.
This issue is specific to `obsm`/`varm` arrays because, unlike `X`/`obsp`/`varp`, and as described [here](https://github.com/single-cell-data/TileDB-SOMA/blob/753d9f7d3ff31237fd2907bc6da17a0c6f1ba070/apis/python/src/tiledbsoma/io/outgest.py#L384-L400), their second dimension doesn't map to the `obs` or `var` axis and can include …
=> Use correct shape for obsm/varm layers in anndata export

python-spec/src/somacore/__init__.py, python-spec/src/somacore/coordinates.py, python-spec/src/somacore/types.py, python-spec/testing/test_coordinates.py
New classes:
* Axis: simple data class storing a name, optional units, and optional scale
* CoordinateSpace: used to define coordinate spaces for spatial data
* CoordinateTransform: abstract base class for coordinate transforms
* AffineTransform: implementation for a generic affine coordinate transform
* ScaleTransform: implementation for a coordinate transform that scales axes (may be isotropic/uniform)
* IdentityTransform: implementation for an identity transform that only applies a name change to axes
=> Add classes for coordinate spaces and transforms

python-spec/src/somacore/coordinates.py, python-spec/testing/test_coordinates.py
PR #227 forgot to add an ellipses with the tuple.
=> Fix type hint for CoordinateSpace `axis`

python-spec/src/somacore/spatial.py
As discussed in https://github.com/single-cell-data/SOMA/pull/219#pullrequestreview-2329701066.
=> Expand spatial dataframe docstrings

python-spec/src/somacore/experiment.py, python-spec/src/somacore/measurement.py, python-spec/src/somacore/query/query.py
This adds dataframes for creating a join table between the scenes and observations/variables. New methods are added to the `ExperimentAxisQuery` class for getting a Arrow array of scene names that relate to the obs or var in the query.
This PR is ready to be reviewed, but should be merged after PR #220
=> Add spatial presence matrices

python-spec/src/somacore/__init__.py, python-spec/src/somacore/ephemeral/collections.py, python-spec/src/somacore/scene.py, python-spec/src/somacore/spatial.py
Rename the `PointCloud` class to `PointCloudDataFrame` for better clarity.
=> Rename `PointCloud` -> `PointCloudDataFrame`

python-spec/src/somacore/collection.py
**Issue and/or context:** As tracked on issue https://github.com/single-cell-data/TileDB-SOMA/issues/2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048).
Note that the intended Python and R API changes are all agreed on and finalized as described in #2407.
**Changes:**
The `Collection.add_new_dataframe` is syntactic sugar on `DataFrame.create`. The latter takes an optional `domain` argument, so the former should as well.
This is not only generally important for https://github.com/single-cell-data/TileDB-SOMA/issues/2407; it is specifically for the cellxgene census builder which uses `add_new_dataframe` exclusively.
**Notes for Reviewer:**
=> Sync `domain` argument between `Collection.add_new_dataframe` and `DataFrame.create`

python-spec/src/somacore/scene.py
This fixes a few typos in the `Scene` class.
=> Fix typos in Scene `add_*` methods

python-spec/src/somacore/ephemeral/collections.py, python-spec/src/somacore/scene.py
* Rename `add_*` -> `add_new_*` for consistency with `Collection` methods.
* Change type specific keywords to be `**kwargs` and refer to class create methods for specific keywords.
=> [python] Update `Scene` `add_*` methods

python-spec/src/somacore/spatial.py
Directly use the `CoordinateSpace` class instead of `axis_names`.
=> Replace `axis_name` with `coordinate_space` in spatial dataframes

python-spec/src/somacore/types.py
This code dates to Feb '23, doesn't seem to be necessary for tests/CI (including Typeguard and mypy) to pass, and seems to be causing issues in TileDB-SOMA CI (e.g. https://github.com/single-cell-data/TileDB-SOMA/issues/3246).
[Here's](https://github.com/ryan-williams/tiledb-scratch/actions/runs/11560662489) a sweep of:
- Python: { 3.9.10, 3.9.19 3.12.7 }
- SOMA: { main, rw/slc (this branch) }
- Typeguard: { 4.2.1, 4.3.0, 4.4.0 }
- Single test case: [`test_dataframe_index_columns.py::test_types_no_errors[soma_joinid-py-slice-index_column_names4-domain4-coords4-expecteds4]`](https://github.com/single-cell-data/TileDB-SOMA/blob/24a74384964c1f7a62938dacb3a644f7488bba6f/apis/python/tests/test_dataframe_index_columns.py#L94-L103) (started failing on Python 3.9, ca. [typeguard#496] / 4.4.0) …
=> rm py3.9 `__subclasscheck__` workaround

python-spec/src/somacore/ephemeral/collections.py, python-spec/src/somacore/scene.py
- Make subcollection always a positional argument (for consistency).
- Fix docstrings for `create` methods (no default value for subcollection).
=> Update Scene subcollection API

python-spec/src/somacore/__init__.py, python-spec/src/somacore/spatial.py
This PR addresses feedback from PR #219 regarding the `MultiscaleImage` API. It includes the following changes:
* Directly take the `CoordinateSpace` as a creation parameter.
* Remove confusing `image_type` property/creation parameter. Use `data_axis_order` instead which uses the axis names the user provided.
* Create the first resolution level when creating the `MultiscaleImage`.
* Require the `add_new_level` to only add images smaller than the base (level=0) image.
* Add a `set` method for adding images that exist outside of SOMA.
* Add a property to check the number of channels in the image.
* Remove `ImageProperties` class.
=> Update the MultiscaleImage API

pyproject.toml, python-spec/src/somacore/base.py, python-spec/src/somacore/experiment.py, python-spec/src/somacore/query/_fast_csr.py, python-spec/src/somacore/query/query.py, python-spec/src/somacore/query/types.py
`_CSRAccumulator` [declares][accumulator args] `{obs,var}_joinids` args of type `npt.NDArray[np.int64]`, but was [passed][accumulator call] `pa.Array`s.
[accumulator args]: https://github.com/single-cell-data/SOMA/blob/python-v1.0.23/python-spec/src/somacore/query/_fast_csr.py#L85-L86
[accumulator call]: https://github.com/single-cell-data/SOMA/blob/python-v1.0.23/python-spec/src/somacore/query/_fast_csr.py#L28-L30
=> `_fast_csr` type fix, docstr/pre-commit tweaks

python-spec/src/somacore/spatial.py
This removes the redundant parameter `has_channel_axis` from the `MultiscaleScale.create` class method. The existence and location of a channel axis is already specified by the `data_axis_order` parameter.
=> Remove unnecessary `has_channel_axis` create param

python-spec/src/somacore/spatial.py
We may add the option to specify additional index columns back to the API in the future, but for the alpha release we would like to constain the spatial dataframes to only be index by spatial indices.
=> Remove ``index_column`` as an option for the spatial dataframes

python-spec/src/somacore/scene.py
Allow user to specify the scene coordinate space on creation.
=> Add `coordinate_space` to `Scene.create`

python-spec/src/somacore/data.py, python-spec/src/somacore/spatial.py, python-spec/src/somacore/types.py
**Issue and/or context:** As tracked on issue https://github.com/single-cell-data/TileDB-SOMA/issues/2407/ [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048).
Note that the intended Python and R API changes are all agreed on and finalized as described in https://github.com/single-cell-data/TileDB-SOMA/issues/2407
**Changes:**
**Notes for Reviewer:**
=> Update docstrings for new-shape feature

python-spec/src/somacore/data.py
Found on
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/12364349712/job/34507422201
in light of
https://github.com/single-cell-data/TileDB-SOMA/pull/3455
=> Sync `DataFrame` `change_domain` with impl repo

python-spec/src/somacore/_mixin.py, python-spec/src/somacore/base.py, python-spec/src/somacore/collection.py, python-spec/src/somacore/coordinates.py, python-spec/src/somacore/data.py, python-spec/src/somacore/experiment.py, python-spec/src/somacore/options.py, python-spec/src/somacore/query/axis.py, python-spec/src/somacore/query/query.py, python-spec/src/somacore/scene.py, python-spec/src/somacore/spatial.py, python-spec/src/somacore/types.py
Convert `Optional[]` to [union types](https://docs.python.org/3/library/stdtypes.html#union-type) in type hints
[SC-61053](https://app.shortcut.com/tiledb-inc/story/61053)
resolves single-cell-data/TileDB-SOMA#3334
=> Convert `Optional[]` to union types

python-spec/src/somacore/coordinates.py, python-spec/testing/test_coordinates.py
The Axis name should never start with "soma_".
=> Prevent `Axis.name` from staring with "soma_"

.pre-commit-config.yaml, README.md, abstract_specification.md
Changes:
1. Add pre-commit action for markdown files  using `mdformat`
2. Remove `prettier` pre-commit action
3. Run pre-commit autoupdate to update repo versions
4. Run the pre-commit, which reformatted MD files
=> Use mdformat for markdown format/lint
